// src/components/AppearancePanel.tsx
import { mySlot, useStore } from '@/store/useStore'
import { ACCENTS, ACCENT_KEYS, HUES, HUE_KEYS } from '@/lib/palette'
import type { AccentKey, CategoryKey, HueKey, ThemeChoice } from '@/lib/palette'
import { Segmented } from '@/components/kit'
import { Input } from '@/components/ui/input'
import { cn } from '@/lib/utils'

function SubHead({ children }: { children: string }) {
  return (
    <div className="mb-2 mt-4 text-[11px] font-semibold uppercase tracking-[0.07em] text-ink-3">
      {children}
    </div>
  )
}

function Swatch({
  color, active, onClick, label, small = false,
}: { color: string; active: boolean; onClick: () => void; label: string; small?: boolean }) {
  return (
    <button
      onClick={onClick}
      aria-pressed={active}
      aria-label={label}
      title={label}
      className={cn(
        'rounded-[9px] border-2',
        small ? 'size-[22px]' : 'size-[26px]',
        active ? 'border-ink' : 'border-transparent',
      )}
      style={{ background: color }}
    />
  )
}

export function AppearancePanel() {
  const settings = useStore((s) => s.settings)
  const categories = useStore((s) => s.categories)
  const setTheme = useStore((s) => s.setTheme)
  const setAccent = useStore((s) => s.setAccent)
  const setCategoryHue = useStore((s) => s.setCategoryHue)
  const setPerson = useStore((s) => s.setPerson)
  const people = useStore((s) => s.people)
  const membership = useStore((s) => s.membership)
  const userId = useStore((s) => s.userId)
  const slot = mySlot({ membership, userId })
  const me = slot ? people.find((p) => p.id === slot) : undefined

  return (
    <div className="pb-2">
      <SubHead>Ваше имя</SubHead>
      {slot ? (
        <>
          <Input
            defaultValue={me?.name ?? ''}
            placeholder="Имя"
            onBlur={(e) => {
              const next = e.target.value.trim()
              if (next && next !== me?.name) setPerson(slot, { name: next })
            }}
          />
          <p className="mt-1.5 text-[12px] leading-relaxed text-ink-3">
            Так вас видит партнёр — на полосе доходов, в покупках и во взносах.
            По умолчанию подставляется начало адреса почты.
          </p>
        </>
      ) : (
        <p className="text-[12.5px] text-ink-3">Загружаем состав бюджета…</p>
      )}

      <SubHead>Тема</SubHead>
      <Segmented<ThemeChoice>
        value={settings.theme}
        onChange={setTheme}
        options={[
          { value: 'auto', label: 'Авто' },
          { value: 'light', label: 'Светлая' },
          { value: 'dark', label: 'Тёмная' },
        ]}
      />

      <SubHead>Основной цвет</SubHead>
      <div className="flex flex-wrap gap-2">
        {ACCENT_KEYS.map((k: AccentKey) => (
          <Swatch
            key={k}
            color={ACCENTS[k].light}
            label={ACCENTS[k].label}
            active={settings.accent === k}
            onClick={() => setAccent(k)}
          />
        ))}
      </div>

      <SubHead>Цвета разделов</SubHead>
      <div className="flex flex-col">
        {categories.map((c) => (
          <div key={c.key} className="flex items-center gap-2.5 py-2">
            <span className="w-[88px] shrink-0 text-[13.5px] text-ink-2">{c.name}</span>
            <div className="flex flex-wrap gap-1.5">
              {HUE_KEYS.map((h: HueKey) => (
                <Swatch
                  key={h}
                  small
                  color={HUES[h].light}
                  label={HUES[h].label}
                  active={settings.categories[c.key as CategoryKey] === h}
                  onClick={() => setCategoryHue(c.key as CategoryKey, h)}
                />
              ))}
            </div>
          </div>
        ))}
      </div>

      <p className="mt-3 text-[12px] leading-relaxed text-ink-3">
        Каждый цвет задан парой значений — для светлой и тёмной темы. Свободного выбора HEX нет
        намеренно: так нельзя получить сочетание, которое станет нечитаемым при смене темы.
      </p>
    </div>
  )
}

// frontend/src/components/AppearancePanel.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import {
  ACCENTS,
  ACCENT_KEYS,
  type AccentKey,
  type ThemeChoice,
  applyTheme,
} from '@/lib/palette'
import { useAuthStore } from '@/stores/auth'
import { useFinanceStore } from '@/stores/finance'
import Segmented from '@/components/kit/Segmented.vue'
import Input from '@/components/ui/Input.vue'
import Button from '@/components/ui/Button.vue'
import { useRouter } from 'vue-router'

const authStore = useAuthStore()
const financeStore = useFinanceStore()
const router = useRouter()

const currentTheme = ref<ThemeChoice>(
  (typeof localStorage !== 'undefined' && (localStorage.getItem('ff_theme') as ThemeChoice)) || 'auto',
)
const currentAccent = ref<AccentKey>(
  (typeof localStorage !== 'undefined' && (localStorage.getItem('ff_accent') as AccentKey)) || 'emerald',
)

const userName = ref(authStore.member?.display_name || authStore.user?.email?.split('@')[0] || '')

function updateTheme(th: ThemeChoice) {
  currentTheme.value = th
  if (typeof localStorage !== 'undefined') localStorage.setItem('ff_theme', th)
  applyCurrentPalette()
}

function updateAccent(acc: AccentKey) {
  currentAccent.value = acc
  if (typeof localStorage !== 'undefined') localStorage.setItem('ff_accent', acc)
  applyCurrentPalette()
}

function applyCurrentPalette() {
  applyTheme({
    theme: currentTheme.value,
    accent: currentAccent.value,
    categories: { d1: 'blue', d2: 'brick', d3: 'green', d4: 'ochre', d5: 'steel' },
  })
}

function saveName() {
  const trimmed = userName.value.trim()
  if (!trimmed || !authStore.slot) return
  financeStore.setPerson(authStore.slot, { name: trimmed })
}

function handleLogout() {
  authStore.logout()
  router.push('/access')
}

onMounted(() => {
  applyCurrentPalette()
})
</script>

<template>
  <div class="flex flex-col gap-4 text-left">
    <div>
      <div class="mb-1 text-[11px] font-semibold uppercase tracking-[0.07em] text-ink-3">
        Ваше имя
      </div>
      <Input
        v-model="userName"
        placeholder="Имя"
        @blur="saveName"
      />
      <p class="mt-1 text-[12px] leading-relaxed text-ink-3">
        Так вас видит партнёр на полосе доходов, в покупках и во взносах.
      </p>
    </div>

    <div>
      <div class="mb-1.5 text-[11px] font-semibold uppercase tracking-[0.07em] text-ink-3">
        Тема
      </div>
      <Segmented
        :model-value="currentTheme"
        :options="[
          { value: 'auto', label: 'Авто' },
          { value: 'light', label: 'Светлая' },
          { value: 'dark', label: 'Тёмная' },
        ]"
        @update:model-value="updateTheme"
      />
    </div>

    <div>
      <div class="mb-1.5 text-[11px] font-semibold uppercase tracking-[0.07em] text-ink-3">
        Основной цвет
      </div>
      <div class="flex flex-wrap gap-2">
        <button
          v-for="k in ACCENT_KEYS"
          :key="k"
          type="button"
          :aria-label="ACCENTS[k].label"
          :title="ACCENTS[k].label"
          :class="[
            'size-7 rounded-xl border-2 transition-all cursor-pointer',
            currentAccent === k ? 'border-ink scale-105 shadow-xs' : 'border-transparent hover:scale-105',
          ]"
          :style="{ background: ACCENTS[k].light }"
          @click="updateAccent(k)"
        />
      </div>
    </div>

    <div class="pt-3 border-t border-line">
      <Button variant="ghost" class="w-full text-destructive hover:bg-destructive-soft" @click="handleLogout">
        Выйти из аккаунта
      </Button>
    </div>
  </div>
</template>
