// src/screens/GoalDetail.tsx
import { useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, Plus } from '@phosphor-icons/react'
import { Card, Callout, Field, Section, Segmented, Tag } from '@/components/kit'
import { Ring } from '@/components/charts'
import { hueColor } from '@/lib/palette'
import { useIsDark } from '@/lib/useTheme'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Slider } from '@/components/ui/slider'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { money, parseMoney, plain } from '@/lib/money'
import { goalMonths, goalMonthly } from '@/lib/finance'
import { addMonths, monthAfter, monthInAfter, monthKey, monthTitle } from '@/lib/dates'
import { contributionStreak, useStore } from '@/store/useStore'
import type { PersonId } from '@/store/types'

type Mode = 'date' | 'amount'

export function GoalDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const goal = useStore((s) => s.goals.find((g) => g.id === id))
  const people = useStore((s) => s.people)
  const setGoalMonthly = useStore((s) => s.setGoalMonthly)
  const contribute = useStore((s) => s.contribute)
  const removeGoal = useStore((s) => s.removeGoal)
  const inflation = useStore((s) => s.settings.inflation)

  const dark = useIsDark()
  const [mode, setMode] = useState<Mode>('date')
  const [addOpen, setAddOpen] = useState(false)
  const [amount, setAmount] = useState('')
  const [by, setBy] = useState<PersonId>('a')

  if (!goal) {
    return (
      <div className="pt-6 text-center text-[14px] text-ink-3">
        Цель не найдена.{' '}
        <button className="text-brand" onClick={() => navigate('/goals')}>К списку</button>
      </div>
    )
  }

  // Ритм считается по взносам именно в эту цель.
  const streak = contributionStreak(goal.movements)
  const filled = new Set(goal.movements.filter((m) => m.amount > 0).map((m) => m.date.slice(0, 7)))
  const last12 = Array.from({ length: 12 }, (_, i) => {
    const k = addMonths(monthKey(), i - 11)
    return { key: k, label: monthTitle(k), filled: filled.has(k) }
  })

  const remaining = Math.max(0, goal.need - goal.have)
  const months = goalMonths(remaining, goal.monthly)
  const progress = goal.need ? goal.have / goal.need : 0
  const min = Math.max(5_000, Math.round((goal.monthly * 0.4) / 5_000) * 5_000)
  const max = Math.max(min + 5_000, Math.round((goal.monthly * 2.6) / 5_000) * 5_000)

  // Во сколько обойдётся та же цель через N месяцев, если она дорожает вместе с рынком.
  const indexed = Math.round(goal.need * Math.pow(1 + inflation, months / 12))

  function addContribution() {
    const v = parseMoney(amount)
    if (!v) return
    contribute(goal!.id, v, by)
    setAmount('')
    setAddOpen(false)
  }

  return (
    <div className="flex flex-col gap-3.5 pt-1">
      <button onClick={() => navigate('/goals')} className="flex items-center gap-1.5 self-start text-[13px] text-ink-2">
        <ArrowLeft size={15} /> Все цели
      </button>

      <Card>
        <div className="mb-4 flex items-center gap-3.5">
          <Ring progress={progress} plan={goal.planPct} hue={goal.hue} size={58} />
          <div>
            <div className="font-display text-[18px] font-semibold tracking-[-0.01em]">{goal.name}</div>
            <div className="text-[13px] text-ink-3 num">
              {plain(goal.have)} из {plain(goal.need)} ₸
            </div>
          </div>
        </div>

        <Segmented<Mode>
          value={mode}
          onChange={setMode}
          options={[
            { value: 'date', label: 'Считаем от даты' },
            { value: 'amount', label: 'Считаем от суммы' },
          ]}
        />

        <div className="pb-1.5 pt-5 text-center">
          <div className="text-[12.5px] tracking-[0.03em] text-ink-3">
            {mode === 'date' ? 'Откладывать в месяц' : 'Цель будет достигнута'}
          </div>
          <div className="mt-1 font-display text-[32px] font-semibold leading-tight tracking-[-0.025em] num">
            {mode === 'date' ? money(goal.monthly) : monthAfter(months - 1)}
          </div>
          <div className="mt-1.5 text-[13px] text-ink-2">
            {mode === 'date'
              ? `Цель закроется в ${monthInAfter(months - 1)}`
              : `При взносе ${money(goal.monthly)} в месяц · ${months} мес.`}
          </div>
        </div>

        <div className="mt-4">
          <Slider
            min={min}
            max={max}
            step={5_000}
            value={[Math.min(max, Math.max(min, goal.monthly))]}
            onValueChange={([v]) => setGoalMonthly(goal.id, v)}
            aria-label="Ежемесячный взнос"
          />
          <div className="mt-1 flex justify-between text-[12px] text-ink-3 num">
            <span>{money(min)}</span>
            <span>{money(max)}</span>
          </div>
        </div>

        <div className="mt-3 border-t border-line pt-3 text-[12.5px] text-ink-2">
          Чтобы успеть за год, нужно {money(goalMonthly(remaining, 12))} в месяц.
        </div>
      </Card>

      <Button className="w-full" onClick={() => setAddOpen(true)}>
        <Plus size={16} weight="bold" /> Пополнить цель
      </Button>

      <Callout title="Цель дорожает вместе с рынком">
        При инфляции {(inflation * 100).toFixed(1).replace('.', ',')}% в год к моменту достижения
        такая же покупка будет стоить около {money(indexed)}. Расчёт выше — в сегодняшних деньгах.
      </Callout>

      <Section title="Ритм цели" />
      <Card>
        <div className="mb-3 flex items-center gap-2.5">
          <b className="text-[14.5px] font-semibold">Пополняем без пропусков</b>
          {streak > 0 && <Tag tone="gold">{streak} мес.</Tag>}
        </div>
        <div className="flex gap-1.5">
          {last12.map((m) => (
            <i
              key={m.key}
              title={m.label}
              className="h-[20px] flex-1 rounded"
              style={{ background: m.filled ? hueColor(goal.hue, dark) : 'var(--track)' }}
            />
          ))}
        </div>
        <p className="mt-3 text-[12.5px] leading-relaxed text-ink-3">
          {streak > 0
            ? 'Считается по взносам именно в эту цель, а не по плану.'
            : 'Закрасится, как только появится первый взнос. Считается по фактическим пополнениям этой цели.'}
        </p>
      </Card>

      <Section title="История цели" />
      <Card flush>
        {goal.movements.length ? (
          goal.movements.map((m) => (
            <div key={m.id} className="flex items-center gap-3 border-b border-line px-4 py-3 last:border-b-0">
              <i className="size-2 shrink-0 rounded-full" style={{ background: `var(--p${m.by})` }} />
              <div className="min-w-0 flex-1">
                <b className="block text-[14.5px] font-medium">
                  {m.amount > 0 ? 'Пополнение' : 'Изъятие'}
                </b>
                <span className="block text-[12.5px] text-ink-3">
                  {new Date(m.date).toLocaleDateString('ru-RU')} ·{' '}
                  {people.find((p) => p.id === m.by)?.name}
                </span>
              </div>
              <span className="shrink-0 text-[14.5px] font-semibold num">
                {m.amount > 0 ? '+' : '−'}{plain(Math.abs(m.amount))}
              </span>
            </div>
          ))
        ) : (
          <div className="px-4 py-6 text-center text-[13px] text-ink-3">
            Взносов пока нет — история появится после первого пополнения
          </div>
        )}
      </Card>

      <button
        onClick={() => { removeGoal(goal.id); navigate('/goals') }}
        className="mb-2 self-center text-[13px] text-ink-3 hover:text-destructive"
      >
        Удалить цель
      </button>

      <Dialog open={addOpen} onOpenChange={setAddOpen}>
        <DialogContent className="max-w-[92vw] rounded-2xl border-line bg-surface sm:max-w-[400px]">
          <DialogHeader><DialogTitle className="font-display">Пополнить «{goal.name}»</DialogTitle></DialogHeader>
          <Field label="Сумма, ₸">
            <Input value={amount} onChange={(e) => setAmount(e.target.value)} inputMode="numeric" placeholder={plain(goal.monthly)} className="num" autoFocus />
          </Field>
          <Field label="Кто вносит">
            <Segmented<PersonId> value={by} onChange={setBy} options={people.map((p) => ({ value: p.id, label: p.name }))} />
          </Field>
          <Button onClick={addContribution} className="w-full">Внести</Button>
        </DialogContent>
      </Dialog>
    </div>
  )
}

// frontend/src/views/GoalDetail.vue
<script setup lang="ts">
import { ref, computed, nextTick, watch } from 'vue'
import { useRouter, useRoute, RouterLink } from 'vue-router'
import { PhArrowLeft, PhPencilSimple, PhPlus, PhMinus } from '@phosphor-icons/vue'
import { useFinanceStore } from '@/stores/finance'
import { useAuthStore } from '@/stores/auth'
import { money, plain, parseMoney, ratePct } from '@/lib/money'
import {
  INFLATION,
  contributionStreak,
  goalDoneMonth,
  goalMonths,
  goalMonthly,
  indexedNeed,
  liveGoals,
  payableAccounts,
  planForecast,
} from '@/lib/finance'
import { addMonths, monthIn, monthKey, monthTitle } from '@/lib/dates'
import { hueColor } from '@/lib/palette'
import { isDark } from '@/lib/theme'
import type { PersonId } from '@/types/finance'

import Card from '@/components/kit/Card.vue'
import Section from '@/components/kit/Section.vue'
import Field from '@/components/kit/Field.vue'
import Hint from '@/components/kit/Hint.vue'
import NumField from '@/components/kit/NumField.vue'
import NumFieldBlur from '@/components/kit/NumFieldBlur.vue'
import SavedMark from '@/components/kit/SavedMark.vue'
import Segmented from '@/components/kit/Segmented.vue'
import Select from '@/components/kit/Select.vue'
import Sheet from '@/components/kit/Sheet.vue'
import Tag from '@/components/kit/Tag.vue'
import Callout from '@/components/kit/Callout.vue'
import { useSavedMark } from '@/components/kit/useSavedMark'
import Ring from '@/components/Ring.vue'
import GoalSheet from '@/components/goals/GoalSheet.vue'
import Button from '@/components/ui/Button.vue'
import Input from '@/components/ui/Input.vue'

type Mode = 'date' | 'amount'
const mode = ref<Mode>('date')

const router = useRouter()
const route = useRoute()
const financeStore = useFinanceStore()
const authStore = useAuthStore()

const goalId = computed(() => route.params.id as string)
// Удалил партнёр — «Цель не найдена», как окно правки (`GoalSheet`): пополнение ушло бы в
// надгробие, а счёт списался бы.
const goal = computed(() => liveGoals(financeStore.goals).find((g) => g.id === goalId.value))
const people = computed(() => financeStore.people)
// Пополнение и снятие двигают тенговую базу счёта: валютный счёт пересчитал бы её по
// курсу при следующей правке и молча потерял сдвиг. Удалённые счета — тоже не сюда.
const accounts = computed(() => payableAccounts(financeStore.accounts))

// План «Сначала долги» (PV-15): пауза выводится из плана, взнос цели не трогается (Р-9).
const plan = computed(() => financeStore.activePlan)
const paused = computed(() => financeStore.pausedGoalIds.has(goalId.value))
const planCushion = computed(() => !!plan.value && plan.value.cushionGoalId === goalId.value)

const remaining = computed(() => (goal.value ? Math.max(0, goal.value.need - goal.value.have) : 0))
const months = computed(() => (goal.value ? goalMonths(remaining.value, goal.value.monthly) : 1))
const progress = computed(() => (goal.value && goal.value.need > 0 ? goal.value.have / goal.value.need : 0))
// Заливка «Ритма цели» — оттенок цели для текущей темы.
const rhythmColor = computed(() => (goal.value ? hueColor(goal.value.hue, isDark.value) : ''))
// Во сколько обойдётся та же цель к сроку, если она дорожает вместе с рынком; взнос 0 — прогноза нет.
const indexed = computed(() => (goal.value ? indexedNeed(goal.value.need, months.value) : null))

// Цель на паузе стоит, пока план не закроет долги с процентами (Н-8 ревью Блока 3): дата —
// от месяца без процентных долгов по прогнозу плана; не закрываются — месяца нет.
const forecast = computed(() => (paused.value && plan.value ? planForecast(plan.value, financeStore.planState(), monthKey()) : null))
const doneMonth = computed(() => goalDoneMonth(months.value, monthKey(), forecast.value ?? undefined))
const doneTitle = computed(() => (doneMonth.value ? monthTitle(doneMonth.value) : paused.value ? 'После плана' : '—'))
const doneLine = computed(() =>
  doneMonth.value ? `Цель закроется в ${monthIn(doneMonth.value)}` : paused.value ? 'Цель закроется после плана' : '',
)

/* ------------------ Взнос полем (исключение из Р-2, владелец 2026-09-25) ------------------ */
// «Сохранено» — по самому взносу, а не по updatedAt цели: пополнение тоже меняет цель, но
// взнос оно не трогает.
const monthlySaved = useSavedMark(
  () => goal.value?.id,
  () => (goal.value ? String(goal.value.monthly) : undefined),
)
function onMonthly(text: string) {
  const v = parseMoney(text)
  if (goal.value && v > 0 && v !== goal.value.monthly) financeStore.setGoalMonthly(goal.value.id, v)
}

const streak = computed(() => (goal.value ? contributionStreak(goal.value.movements || []) : 0))
const filled = computed(() =>
  new Set((goal.value?.movements || []).filter((m) => m.amount > 0).map((m) => m.date.slice(0, 7))),
)
const last12 = computed(() =>
  Array.from({ length: 12 }, (_, i) => {
    const k = addMonths(monthKey(), i - 11)
    return { key: k, label: monthTitle(k), filled: filled.value.has(k) }
  }),
)

/* ------------------ Пополнение / Снятие ------------------ */
const openDepositModal = ref(false)
const depositOperation = ref<'deposit' | 'withdraw'>('deposit')
const depositAmount = ref('')
const depositBy = ref<PersonId>('a')
const depositAccountId = ref<string>('')
const depositNote = ref('')
// Сумма — сразу под пальцем (React `autoFocus`): лист вставляется после открытия, атрибут не сработал бы.
const depositAmountRef = ref<HTMLElement | null>(null)
watch(openDepositModal, (open) => {
  if (open) void nextTick(() => depositAmountRef.value?.querySelector('input')?.focus())
})

// История — новые сверху по дате: слияние хранит «новые первыми», взнос дописывается в конец.
const history = computed(() =>
  [...(goal.value?.movements ?? [])].sort((a, b) => b.date.localeCompare(a.date)),
)

function applyDeposit() {
  const v = parseMoney(depositAmount.value)
  if (!v || !goal.value) return

  if (depositOperation.value === 'deposit') {
    financeStore.contribute(goal.value.id, v, depositBy.value, depositNote.value.trim() || undefined)
    // Сдвиг остатка, а не сверка: отметки оплат до взноса продолжают считаться.
    if (depositAccountId.value) financeStore.shiftAccountAmount(depositAccountId.value, -v)
  } else {
    financeStore.withdraw(goal.value.id, v, depositBy.value, depositNote.value.trim() || undefined)
    if (depositAccountId.value) financeStore.shiftAccountAmount(depositAccountId.value, v)
  }

  depositAmount.value = ''
  depositNote.value = ''
  depositAccountId.value = ''
  openDepositModal.value = false
}

/* ------------------ Редактирование цели ------------------ */
// Поля окна пишутся сами по уходу из поля (`GoalSheet`); viewer окна не открывает (Р-12).
const openEditModal = ref(false)
</script>

<template>
  <div v-if="!goal" class="pt-6 text-center text-[14px] text-ink-3">
    Цель не найдена.
    <button class="text-brand font-medium cursor-pointer" @click="router.push('/')">
      К списку
    </button>
  </div>

  <div v-else class="flex flex-col gap-3.5 pt-1">
    <button
      type="button"
      class="flex items-center gap-1.5 self-start text-[13px] text-ink-2 hover:text-ink cursor-pointer"
      @click="router.push('/')"
    >
      <PhArrowLeft :size="15" /> Все цели
    </button>

    <Card>
      <div class="mb-4 flex items-center gap-3.5">
        <Ring :progress="progress" :plan="goal.planPct" :hue="goal.hue" :size="58" />
        <div class="min-w-0 flex-1">
          <div class="truncate font-display text-[18px] font-semibold tracking-[-0.01em] text-ink">
            {{ goal.name }}
          </div>
          <div class="text-[13px] text-ink-3 num">
            {{ plain(goal.have) }} из {{ plain(goal.need) }} ₸
          </div>
        </div>
        <button
          v-if="!authStore.isViewer"
          type="button"
          aria-label="Изменить цель"
          class="grid size-9 shrink-0 place-items-center rounded-xl border border-line text-ink-2 hover:bg-surface-2 hover:text-ink cursor-pointer"
          @click="openEditModal = true"
        >
          <PhPencilSimple :size="17" />
        </button>
      </div>

      <Segmented
        v-model="mode"
        :options="[
          { value: 'date', label: 'Считаем от даты' },
          { value: 'amount', label: 'Считаем от суммы' },
        ]"
      />

      <div class="pb-1.5 pt-5 text-center">
        <div class="text-[12.5px] tracking-[0.03em] text-ink-3">
          {{ mode === 'date' ? 'Откладывать в месяц' : 'Цель будет достигнута' }}
        </div>
        <div class="mt-1 font-display text-[32px] font-semibold leading-tight tracking-[-0.025em] num text-ink">
          {{ mode === 'date' ? money(goal.monthly) : doneTitle }}
        </div>
        <div class="mt-1.5 text-[13px] text-ink-2">
          {{ mode === 'date' ? doneLine : `При взносе ${money(goal.monthly)} в месяц · ${months} мес.` }}
        </div>
        <div v-if="paused && doneMonth" class="text-[12px] text-ink-3">после плана</div>
      </div>

      <!-- Взнос вводится числом, а не ползунком (исключение из Р-2, владелец 2026-09-25). Viewer — только сумма. -->
      <div v-if="!authStore.isViewer" class="mt-4">
        <div class="-mb-3.5 flex justify-end">
          <SavedMark :on="monthlySaved" />
        </div>
        <Field label="Откладывать в месяц, ₸">
          <NumFieldBlur :initial="plain(goal.monthly)" @commit="onMonthly" />
        </Field>
      </div>

      <div class="mt-3 border-t border-line pt-3 text-[12.5px] text-ink-2">
        Чтобы успеть за год, нужно {{ money(goalMonthly(remaining, 12)) }} в месяц.
      </div>
    </Card>

    <Callout v-if="paused" title="На паузе ради плана">
      Взнос {{ money(goal.monthly) }} идёт в досрочку самого дорогого долга — так семья отдаст банку
      меньше. Цель возобновится сама, когда долги с процентами закроются, или когда вы отмените план.
      <RouterLink to="/money/plan" class="font-medium text-brand">Открыть план</RouterLink>
    </Callout>
    <Callout v-else-if="planCushion" tone="good" title="Подушка плана: взносы продолжаются">
      Пока в ней меньше месяца обязательных списаний, шаг плана — пополнить её.
      <RouterLink to="/money/plan" class="font-medium text-brand">Открыть план</RouterLink>
    </Callout>

    <div class="flex gap-2">
      <Button
        class="flex-1"
        @click="
          depositOperation = 'deposit';
          openDepositModal = true;
        "
      >
        <PhPlus :size="16" weight="bold" /> Пополнить
      </Button>
      <Button
        variant="outline"
        class="flex-1 bg-surface-2"
        @click="
          depositOperation = 'withdraw';
          openDepositModal = true;
        "
      >
        <PhMinus :size="16" weight="bold" /> Снять
      </Button>
    </div>

    <Callout v-if="indexed !== null" title="Цель дорожает вместе с рынком">
      При инфляции {{ ratePct(INFLATION, 1) }} в год к моменту достижения
      такая же покупка будет стоить около {{ money(indexed) }}. Расчёт выше — в сегодняшних деньгах.
    </Callout>

    <!-- Ритм цели -->
    <Section title="Ритм цели" />
    <Card>
      <div class="mb-3 flex items-center gap-2.5">
        <b class="text-[14.5px] font-semibold text-ink">Пополняем без пропусков</b>
        <Hint>
          {{
            streak > 0
              ? 'Считается по взносам именно в эту цель, а не по общему плану.'
              : 'Закрасится, как только появится первый взнос в эту цель.'
          }}
        </Hint>
        <Tag v-if="streak > 0" tone="gold">{{ streak }} мес.</Tag>
      </div>
      <div class="flex gap-1.5">
        <i
          v-for="m in last12"
          :key="m.key"
          :title="m.label"
          class="h-[20px] flex-1 rounded transition-colors"
          :style="{ background: m.filled ? rhythmColor : 'var(--track)' }"
        />
      </div>
    </Card>

    <!-- История взносов -->
    <Section title="История цели" />
    <Card flush>
      <div
        v-for="m in history"
        :key="m.id"
        class="flex items-center gap-3 border-b border-line px-4 py-3 last:border-b-0"
      >
        <i class="size-2 shrink-0 rounded-full" :style="{ background: `var(--p${m.by})` }" />
        <div class="min-w-0 flex-1 text-left">
          <b class="block text-[14.5px] font-medium text-ink">
            {{ m.amount > 0 ? 'Пополнение' : 'Снятие' }}
          </b>
          <span class="block text-[12.5px] text-ink-3">
            {{ new Date(m.date).toLocaleDateString('ru-RU') }} ·
            {{ people.find((p) => p.id === m.by)?.name || 'Участник' }}
            <span v-if="m.note">· {{ m.note }}</span>
          </span>
        </div>
        <span
          :class="[
            'shrink-0 text-[14.5px] font-semibold num',
            m.amount > 0 ? 'text-brand' : 'text-ink-2',
          ]"
        >
          {{ m.amount > 0 ? '+' : '−' }}{{ plain(Math.abs(m.amount)) }} ₸
        </span>
      </div>
      <div v-if="!(goal.movements && goal.movements.length)" class="px-4 py-6 text-center text-[13px] text-ink-3">
        Взносов пока нет — история появится после первого пополнения
      </div>
    </Card>

    <!-- Окно: Пополнить / Снять -->
    <Sheet
      :open="openDepositModal"
      :title="depositOperation === 'deposit' ? `Пополнить «${goal.name}»` : 'Снять средства'"
      @close="openDepositModal = false"
    >
      <div ref="depositAmountRef">
        <Field label="Сумма, ₸">
          <NumField
            v-model="depositAmount"
            :placeholder="depositOperation === 'deposit' ? plain(goal.monthly) : '10 000'"
            class="mb-3"
          />
        </Field>
      </div>

      <Field v-if="accounts.length > 0" :label="depositOperation === 'deposit' ? 'Списать со счёта (опционально)' : 'Зачислить на счёт (опционально)'">
        <Select
          v-model="depositAccountId"
          :options="[
            { value: '', label: 'Не списывать со счетов' },
            ...accounts.map((a) => ({ value: a.id, label: `${a.name} (${money(a.amount)})` })),
          ]"
          class="mb-3"
        />
      </Field>

      <Field v-if="people.length > 1" label="Кто вносит" group>
        <Segmented v-model="depositBy" :options="people.map((p) => ({ value: p.id, label: p.name }))" />
      </Field>

      <Field label="Примечание">
        <Input v-model="depositNote" placeholder="Премия, накопления…" class="mb-3" />
      </Field>

      <Button :disabled="parseMoney(depositAmount) <= 0" class="w-full mt-2" @click="applyDeposit">
        {{ depositOperation === 'deposit' ? 'Внести' : 'Снять' }}
      </Button>
    </Sheet>

    <!-- Окно: Изменить цель -->
    <GoalSheet
      :goal-id="openEditModal && !authStore.isViewer ? goal.id : null"
      @close="openEditModal = false"
      @removed="router.push('/')"
    />
  </div>
</template>
